http://localhost:8080/api/osoba/1

###

http://localhost:5000/api/persons/2

###

http://localhost:5000/api/budget/2
###

http://localhost:5000/api/projects/2

###

http://localhost:5000/api/grants/2

###

http://localhost:5000/api/council/2
###

http://localhost:5000/api/stats/2/2019?type=2
###

http://localhost:5000/api/resolutions?creatorId=1007
###

http://localhost:5000/api/integration/rss/1
