version: 2
jobs:
  build_front:
    docker:
      - image: library/node:10
    steps:
      - checkout
      - run: cd frontend && npm install
      - run: cd frontend && npm install -g @angular/cli
      - run: cd frontend && ng build --prod
  build_back:
    docker:
      - image: maven/3.6.0-jdk-12
    steps:
      - checkout
      - run: mvn package
      - store_artifacts:
        path: backend/target/samosprava-0.0.1-SNAPSHOT.jar
workflows:
  version: 2
  build_all:
    jobs:
      - build_back:
          requires:
            - build_front