version: 2
jobs:
  build:
    docker:
      - image: library/node:10
    steps:
      - checkout
      - run: cd frontend && npm install
      - run: cd frontend && npm install -g @angular/cli
      - run: cd frontend && ng build --prod
workflows:
  version: 2
  build_and_test:
    jobs:
      - build