version: 2
jobs:
  build_front:
    docker:
      - image: library/node:10
    steps:
      - checkout
      - run: cd frontend && npm install
      - run: cd frontend && npm install -g @angular/cli
      - run: cd frontend && ng build --prod
      - persist_to_workspace:
          root: backend/src/main/resources
          paths: 
            - static
  build_back:
    docker:
      - image: library/maven:3.6.0-jdk-12
    steps:
      - checkout
      - attach_workspace:
          at: backend/src/main/resources
      - run: cd backend && mvn package
      - store_artifacts:
          path: backend/target/samosprava-0.0.1-SNAPSHOT.jar
          destination: samosprava-0.0.1-SNAPSHOT.jar
  sonar:
    docker:
      - image: library/maven:3.6.0-jdk-12
    steps:
      - checkout
      - run: cd backend && mvn compile verify install sonar:sonar -Dsonar.login=$SONAR_TOKEN
  test:
    docker:
      - image: library/maven:3.6.0-jdk-12
    steps:
      - checkout
      - run: cd backend && mvn compile
      - store_test_results:
          path: backend/target/surefire-reports
workflows:
  version: 2
  build_all:
    jobs:
      - build_front:
          requires:
            - test
      - build_back:
          requires:
            - build_front
      - sonar:
          requires:
            - test
      - test
